### ISSUE TITLE
Partial refresh

### ISSUE THREAD

**Issue by KenjiYANAGAWA** [waveshare/IT8951#15]
Is there a way to partially refresh the screen instead of a full refresh?

I am asking this because I want to add lines smoothly as quickly as possible, but the refresh speed is too slow and I thought that is because it has to refresh the whole screen now.

**Comment by humblewizard** [comment]
Why has no one answer this question?

**Comment by pvginkel** [comment]
I'm not sure if this answers the question, but I was looking for a way to update the screen without having it flash to black. If this is what you're looking for, you need to use EPD_IT8951_1bp_Refresh with the A2_Mode. 4bpp will always flash to black, 1bpp will not.

You do have to do a full refresh now and again. The Wiki goes into this.
